### ISSUE TITLE
i think better-sqlite changed it's location and now the driver is looking in weird places?

### ISSUE THREAD

**Issue by earonesty** [craigmulligan/website#14]
setup error Error: Failed to open the database. - Could not locate the bindings file. Tried:
     → C:\Users\erik\arcade\node_modules\better-sqlite3\build\better_sqlite3.node
     → C:\Users\erik\arcade\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
     → C:\Users\erik\arcade\node_modules\better-sqlite3\build\Release\better_sqlite3.node

**Comment by earonesty** [comment]
added this to my package.json:

```
"prepare": "cd node_modules/better-sqlite3 && yarn build-release"
```

then the problem goes away

**Comment by craigmulligan** [comment]
Glad you sorted it out.
